version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd1234
      MYSQL_USER: pymkt
      MYSQL_PASSWORD: rootpwd1234
      MYSQL_DATABASE: pydbdev

    ports:
      - '8889:3306'
    
    volumes:
      - data:/var/lib/mysql

  api:
    restart: always
    depends_on:
      - db
    build: ./backend
    environment:
      PORT: 8080
      
      CLIENT_KEY: Est03sMyPub1ck3yKlY3nt.!
      ADMIN_KEY: Est03sMyPub1ck3y@Dmin.!
      
      MYSQL_USER: pymkt
      MYSQL_ROOT_PASSWORD: rootpwd1234

      DB_USER: pymkt
      DB_PASS: rootpwd1234
      DB_PORT: 3306
    ports:
      - '8081:8080'
    volumes:
      - ./backend:/api

  web:
    build: ./frontend
    # restart: on-failure
    ports:
      - '5700:4200'
    depends_on:
      - api    
    command: npm run start:dev


volumes:
  data:


