version: '3.8'

services:
  db:
    restart: always
    image: mysql:8
    env_file:
      - ./config/db.env
    environment:
      - TZ=America/Santiago
    ports:
      - '8889:3306'
    volumes:
      - data:/var/lib/mysql
    networks:
      - red_privada

  minio:
    restart: always
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - ./config/minio.env  
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - red_privada

  api:
    restart: always
    depends_on:
      - db 
      - minio
    build: ./backend
    env_file:
      - ./config/api.env
    ports:
      - '8081:8080'
    volumes:
      - ./backend:/api
    environment:
      VIRTUAL_HOST: api.pymesmkt.informatica.uv.cl
    networks:
      - red_privada
      - red_proxy

  web:
    restart: always
    depends_on:
      - api
    ports:
      - 80:4200
    build: ./frontend
    volumes:
      - ./frontend:/web
    environment:
      VIRTUAL_HOST: pymesmkt.informatica.uv.cl
    networks:
      - red_privada
      - red_proxy
    
volumes:
  data:
  minio_data:

networks:                  # Definir redes
  red_proxy:               # Nombre de una red
    external: true         # Indica que es una red externa al docker-compose
    name: nginx-proxy      # Nombre de la Red de uso publico entre Docker
  red_privada: 