version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd1234
      MYSQL_USER: pymkt
      MYSQL_PASSWORD: rootpwd1234
      MYSQL_DATABASE: pydbdev
    ports:
      - '8889:3306'
    volumes:
      - data:/var/lib/mysql

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001

  api:
    restart: always
    depends_on:
      - db 
      - minio
    build: ./backend
    environment:
      PORT: 8080
      CLIENT_KEY: Est03sMyPub1ck3yKlY3nt.!
      ADMIN_KEY: Est03sMyPub1ck3y@Dmin.!
      MYSQL_USER: pymkt
      MYSQL_ROOT_PASSWORD: rootpwd1234
      DB_USER: pymkt
      DB_PASS: rootpwd1234
      DB_PORT: 3306
    ports:
      - '8081:8080'
    command: npm run dev
    volumes:
      - ./backend:/api

  web:
    restart: always
    depends_on:
      - api
    ports:
      - '5700:4200'
    build: ./frontend
    volumes:
      - ./frontend:/web

volumes:
  data:
  minio_data: